#scheduled job
#minute,hour, day, month, weekday
#@hourly, @reboot, @daily, @monthly

apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cron
spec:
  # at every minute
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron
              image: busybox
              command: ["sh", "-c", "date; echo Hello from CronJob!"]
          restartPolicy: Never
