apiVersion: v1
kind: Pod
metadata:
  name: cm-vol-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "ls -lart /config/ && sleep 3600"]
      volumeMounts:
        - name: config-vol
          mountPath: /config
  volumes:
    - name: config-vol
      configMap:
        name: app-config