apiVersion: v1
kind: Pod
metadata:
  name: secret-vol-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "cat /secrets/username && sleep 3600"]
      volumeMounts:
        - name: secret-vol
          mountPath: /secrets
  volumes:
    - name: secret-vol
      secret:
        secretName: db-secret
