apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "env | grep username && sleep 3600"]
      envFrom:
        - secretRef:
            name: db-secret
